# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_url: https://bedoyadaniel.github.io/
site_name: My Docs
site_dir: generated/



theme:
  name: material

plugins:
  - search
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      docs_structure: folder
      fallback_to_default: true
      deafult_language: en
      languages:
        en:
          name: English
          build: true
          default: true
        es:
          name: Español
          build: true
