# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_url: https://example.com
site_name: My Docs
theme:
  name: material

plugins:
  - projects: #Permite multi-idioma
      log_level: debug
      projects_dir: languages 
#  - search  #habilita barra de búsqueda
  - offline #facilita consulta y navegación del sitio offline
  - privacy: #plug-in para cargar recursos localmente, reducir tracking
      assets_exclude: #Permitir sistema de comentarios
        - giscus.app/*
  - typeset #permite colocar íconos como parte de headers
  - document-dates:
      position: top            # Display position: top (after title)  bottom (end of document)
      exclude:                 # List of excluded files
       - index.md              # Exclude specific file
       - explainers/index.md
       - how-tos/index.md
       - references/index.md
       - tutorials/index.md

extra_javascript:
  - path: assets/javascript/extra.js

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - admonition #cuadros de texto
  - pymdownx.details #cuadros de texto
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list #permite agregar html dentro del markdown
  - md_in_html #permite desplegar grids
  - pymdownx.blocks.caption #caption para imágenes
  - pymdownx.emoji: #permite agregar íconos y emojies con códigos cortos
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - material.extensions.preview:
      configurations:
        - sources: 
            exclude:
              - explainers/index.md
              - how-tos/index.md
              - references/index.md
              - tutorials/index.md
              - index.md
          targets: 
            include:
              - references/*
