# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_url: https://bedoyadaniel.github.io/
site_name: My Docs
site_dir: generated/



theme:
  name: material

plugins:
  - search
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      docs_structure: folder
      fallback_to_default: true
      default_language: en
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
