# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_url: https://bedoyadaniel.github.io/
site_name: My Docs
site_dir: generated/



theme:
  name: material

nav:
  - Home: index.md
  - Topic1: explainers/index.md

plugins:
  - search
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
        - locale: es
          name: Español
          default: true
          build: true
