# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_url: https://example.com
site_name: My Docs
theme:
  name: material

plugins:
  - projects:
      cache: false
      projects_dir: langu