# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_url: https://bedoyadaniel.github.io/
site_name: My Docs
site_dir: generated/



theme:
  name: material

plugins:
  - projects:
      log_level: debug
      cache: false
      projects_dir: languages