
site_name: Mi Documentación

theme:
  language: es
  name: material
  features:
    - navigation.sections
    - navigation.tabs

plugins:
  - search

extra:
  alternate:
    - name: English
      link: ../en/
      lang: en
    - name: Español
      link: .
      lang: es
