site_name: SocialTIC Forensics
site_url: https://socialtic.github.io/forensics/
site_description: Documentación para investigaciones forenses consentidas en Sociedad Civil
docs_dir: '../docs/es'
site_dir: '../generated'
repo_url: https://github.com/Socialtic/forensics
edit_uri: edit/main/docs/es/
copyright: Creative Commons CC BY-SA

nav:
  - Home: 
    - Inicio: 'index.md'
    - Primeros pasos: iniciar.md
    - Hoja de ruta: 'hoja-de-ruta.md'
    - Comunidad: 'comunidad/index.md'
  - Explainers:
    - Inicio: 'explainers/index.md'
    - Explainer introductorio a forense digital: 'explainers/01-explainer-introduccion-forense-digital/01-explainer-introduccion-forense-digital.md'
    - Explainer de riesgos y amenazas: 'explainers/02-explainer-riesgos-amenazas/02-explainer-riesgos-amenazas.md'
    - Principios para forense basada en logs en Android: 'explainers/03-explainer-forense-logs-android/03-explainer-forense-logs-android.md'
  - Tutoriales: 
    - Inicio: 'tutorials/index.md'
  - Guías how-to:
    - Inicio: 'how-tos/index.md'
    - ¿Cómo obtener y documentar consentimiento informado?: 'how-tos/01-como-obtener-consentimiento-informado/01-como-obtener-consentimiento-informado.md'
  - Referencias:
    - Inicio: 'references/index.md'
    - Diccionario AndroidQF: 'references/01-reference-diccionario-androidqf/01-reference-diccionario-androidqf.md'
  - Comunidad:
    - Comunidad de práctica: 'comunidad/index.md'
    - ¿Por qué contribuir con este repositorio?: 'comunidad/por-que-contribuir.md'
    - ¿Cómo colaborar con este repositorio?: 'comunidad/como-colaborar.md'
    - Mejores prácticas para el idioma español: 'comunidad/guia-idioma-es.md'
    - Traducciones y localizaciones: 'comunidad/como-localizar-l10n.md'
    - Licencia de uso: 'comunidad/licencia.md'
    - Código de conducta: 'comunidad/codigo-de-conducta.md'
    - Limitación de responsabilidades: 'comunidad/limitacion-responsabilidad.md'

theme: 
  name: material
  custom_dir: '../overrides/'
  logo: assets/img/ST_logo-01.png
  language: es
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.view
    - content.action.edit
    - navigation.instant
    - navigation.top
    - announce.dismiss
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - toc.integrate

    


extra:
  alternate: 
    - name: Español
      link: /
      lang: es
    - name: English
      link: /en/
      lang: en   
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/socialtic
    - icon: fontawesome/brands/github
      link: https://github.com/socialtic/forensics/
    - icon: material/web
      link: https://socialtic.org

plugins:
  - search
  - offline

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.blocks.caption

