site_name: SocialTIC Forensics
site_url: https://socialtic.github.io/forensics/en/
site_description: Documentation for consensual forensic investigations in civil society
docs_dir: '../../docs/en'
site_dir: '../../generated/en'
repo_url: https://github.com/Socialtic/forensics
edit_uri: edit/main/docs/es/

nav:
  - Home: 
    - Inicio: 'index.md'
    - Index of contents: 'index-contents.md'
  - Explainers:
    - Home: 'explainers/index.md'
    - Introduction to digital forensics: 'explainers/01-explainer-introduction-digital-forensics/01-explainer-introduction-digital-forensics.md'
    - Risks, threats and mitigatiosn fo forensic labs: 'explainers/02-explainer-risks-threats/02-explainer-risks-threats.md'
    - Intro to log-based forensics on Android: 'explainers/03-explainer-log-forensics-android/03-explainer-log-forensics-android.md'
  - Tutorials: 
    - Home: 'tutorials/index.md'
  - How-to's:
    - Home: 'how-tos/index.md'
    - Obtain and document informed consent: 'how-tos/01-how-to-obtain-informed-consent/01-how-to-obtain-informed-consent.md'
  - Reference:
    - Home: 'references/index.md'
    - AndroidQF output file dictionary: 'references/01-reference-androidqf-dictionary/01-reference-androidqf-dictionary.md'

theme: 
  name: material
  custom_dir: '../../overrides/'
  logo: assets/img/ST_logo-01.png
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - header.autohide
    - announce.dismiss

extra:
  alternate: 
    - name: Español
      link: /
      lang: es
    - name: English
      link: /en/
      lang: en   
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/socialtic
    - icon: fontawesome/brands/github
      link: https://github.com/socialtic/forensics/
    - icon: material/web
      link: https://socialtic.org

plugins:
  - search     

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
