site_name: SocialTIC Forensics
site_url: https://bedoyadaniel.github.io/forensics/en/
site_description: Documentation for consensual forensic investigations in civil society
docs_dir: '../../docs/en'
site_dir: '../../generated/en'
repo_url: https://github.com/Socialtic/forensics
edit_uri: edit/main/docs/en/
copyright: MVT License


nav:
  - Home: 
    - Inicio: 'index.md'
    - Getting started: 'getting-started.md'
    - Roadmap: 'roadmap.md'
    - Community: 'community/index.md'
  - Explainers:
    - Home: 'explainers/index.md'
    - Introduction to digital forensics: 'explainers/01-explainer-introduction-digital-forensics/01-explainer-introduction-digital-forensics.md'
    - Risks, threats and mitigations fo forensic labs: 'explainers/02-explainer-risks-threats/02-explainer-risks-threats.md'
    - Introduction to log-based forensics on Android: 'explainers/03-explainer-log-forensics-android/03-explainer-log-forensics-android.md'
  - Tutorials: 
    - Home: 'tutorials/index.md'
  - How-to's:
    - Home: 'how-tos/index.md'
    - Obtain and document informed consent: 'how-tos/01-how-to-obtain-informed-consent/01-how-to-obtain-informed-consent.md'
    - Enable developer options on Android: 'how-tos/02-how-to-enable-developer-options/02-how-to-enable-developer-options.md'
    - Enable ADB on Android: 'how-tos/03-how-to-enable-adb/03-how-to-enable-adb.md'    
    - Extract a bugreport on Android: 'how-tos/05-how-to-extract-bugreport/05-how-to-extract-bugreport.md'    
    - Perform an extraction using AndroidQF: 'how-tos/04-how-to-extract-with-androidqf/04-how-to-extract-with-androidqf.md'    
  - Reference:
    - Home: 'references/index.md'
    - Glossary: 'references/00-glossary.md'
    - AndroidQF output file dictionary: 'references/01-reference-androidqf-dictionary/01-reference-androidqf-dictionary.md'
    - MVT bugreport output file dictionary: 'references/02-reference-mvt-bugreport-dictionary/02-reference-mvt-bugreport-dictionary.md'
  - Community:
    - Consensual forensics community: 'community/index.md'
    - Supporting this effort: 'community/why-support.md'
    - How can I collaborate?: 'community/how-to-contribute.md'
    - Contributors: 'community/contributors.md'
    - Best practices for English language: 'community/language-guide-en.md'
    - Additional translation and localization efforts: 'community/translations-localization-l10n.md'
    - License of contents: 'community/license.md'
    - Code of conduct: 'community/code-of-conduct.md'
    - Limitation of responsibilities: 'community/limitation-of-responsibility.md'

theme: 
  name: material
  custom_dir: '../../overrides/'
  logo: assets/img/ST_logo-01.png
  favicon: assets/img/ST_logo-01-bn.png
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.highlight #Resalta las coincidencias en el recurso que se abre luego de una búsqueda
    - search.suggest #Sugerencias de búsqueda
    - search.share #agrega botón para compartir en la búsqueda
    - navigation.path #Permite ver breadcrumbs, solo versión insider
    - navigation.tabs #Permite visualizar seccions como tabs
    - navigation.tabs.sticky #Tabs se mantienen fijos en parte alta de la página
    - navigation.indexes #Navega directamente al index de cada carpeta
    - navigation.instant #Carga recursos internos utilizando XHR, para mejorar eficiencia en carga de páginas
    - navigation.instant.prefetch #Reduce tiempo de carga percibido al cargar páginas internas cuando la persona se posiciona sobre link
    - navigation.sections #evita comprimir items del menú en grupos
    - navigation.top #Agrega botón para regresar al inicio
    - navigation.tracking #Sigue la navegación del usuario en la URL
    - content.action.view #Agrega botón de ver fuente
    - content.action.edit #Agrega botón de edición
    - toc.follow #Sigue la navegación del usuario en la tabla de contenidos 
    - toc.integrate #La tabla de contenidos está integrada a la barra de  la izquierda
    - navigation.footer #Agrega botones de contenido actual y contenido siguiente

extra_css:
  - assets/css/extra.css


extra:
  alternate: #configuración de idiomas
    - name: Español
      link: /es/
      lang: es
    - name: English
      link: /en/
      lang: en  
    - name: Português   
      link: /pt-br/
      lang: pt-br
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/socialtic
    - icon: fontawesome/brands/github
      link: https://github.com/socialtic/forensics/
    - icon: material/web
      link: https://socialtic.org

plugins:
  - search  #habilita barra de búsqueda
  - offline #facilita consulta y navegación del sitio offline
  - privacy:  #plug-in para cargar recursos localmente, reducir tracking
      external_assets_exclude: #Permitir sistema de comentarios
        - giscus.app/*
  - typeset #permite colocar íconos como parte de headers
  - document-dates:
      position: top            # Display position: top (after title)  bottom (end of document)
      exclude:                 # List of excluded files
       - index.md              # Exclude specific file
       - explainers/index.md
       - how-tos/index.md
       - references/index.md
       - tutorials/index.md

markdown_extensions:
  - admonition #cuadros de texto
  - pymdownx.details #cuadros de texto
  - pymdownx.superfences #cuadros de texto
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list #permite agregar html dentro del markdown  
  - md_in_html #permite desplegar grids
  - pymdownx.blocks.caption #caption para imágenes
  - pymdownx.emoji: #permite agregar íconos y emojies con códigos cortos
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - material.extensions.preview:
      configurations:
        - sources: 
            exclude:
              - explainers/index.md
              - how-tos/index.md
              - references/index.md
              - tutorials/index.md
              - index.md
          targets: 
            include:
              - references/*