site_name: SocialTIC Forensics
site_url: https://socialtic.github.io/forensics/en/
site_description: Documentation for consensual forensic investigations in civil society
docs_dir: '../../docs/en'
site_dir: '../../generated/en'


nav:
  - Home: 'index.md'
  - Explainers:
    - Inicio: '1-explainers/index.md'
  - Tutorials: 
    - Inicio: '2-tutorials/index.md'
  - How-to's:
    - Inicio: '3-how-tos/index.md'
  - Reference:
    - Inicio: '4-reference/index.md'

theme: 
  name: material
  custom_dir: '../../overrides/'
  logo: assets/img/ST_logo-01.png
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

  extra:
    alternate: 
     - name: Español
       link: /es/
       lang: es
     - name: English
       link: /en/
       lang: en   

  plugins:
  - search:
      separator: '[\s\-\.\_]'
      lang: en
          


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
