site_name: SocialTIC Forensics
site_url: https://forensics.socialtic.org/en/
site_description: Documentation for consensual forensic investigations in civil society
docs_dir: '../../docs/en'
site_dir: '../../generated/en'
repo_url: https://github.com/Socialtic/forensics
edit_uri: edit/main/docs/en/
copyright: MVT License


nav:
  - Home: 
    - Inicio: 'index.md'
    - Getting started: 'getting-started.md'
    - Roadmap: 'roadmap.md'
    - Community: 'community/index.md'
  - Explainers:
    - Home: 'explainers/index.md'
    - Introduction to digital forensics: 'explainers/01-explainer-introduction-digital-forensics/01-explainer-introduction-digital-forensics.md'
    - Risks, threats and mitigations fo forensic labs: 'explainers/02-explainer-risks-threats/02-explainer-risks-threats.md'
    - Introduction to log-based forensics on Android: 'explainers/03-explainer-log-forensics-android/03-explainer-log-forensics-android.md'
  - Tutorials: 
    - Home: 'tutorials/index.md'
  - How-to's:
    - Home: 'how-tos/index.md'
    - Obtain and document informed consent: 'how-tos/01-how-to-obtain-informed-consent/01-how-to-obtain-informed-consent.md'
  - Reference:
    - Home: 'references/index.md'
    - AndroidQF output file dictionary: 'references/01-reference-androidqf-dictionary/01-reference-androidqf-dictionary.md'
  - Community:
    - Consensual forensics community: 'community/index.md'
    - Supporting this effort: 'community/why-support.md'
    - How can I collaborate?: 'community/how-to-contribute.md'
    - Best practices for English language: 'community/language-guide-en.md'
    - Additional translation and localization efforts: 'community/translations-localization-l10n.md'
    - License of contents: 'community/license.md'
    - Code of conduct: 'community/code-of-conduct.md'
    - Limitation of responsibilities: 'community/limitation-of-responsibility.md'

theme: 
  name: material
  custom_dir: '../../overrides/'
  logo: assets/img/ST_logo-01.png
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.highlight #Resalta las coincidencias en el recurso que se abre luego de una búsqueda
    - search.suggest #Sugerencias de búsqueda
    - search.share #agrega botón para compartir en la búsqueda
    - navigation.path #Permite ver breadcrumbs, solo versión insider
    - navigation.tabs #Permite visualizar seccions como tabs
    - navigation.tabs.sticky #Tabs se mantienen fijos en parte alta de la página
    - navigation.indexes #Navega directamente al index de cada carpeta
    - navigation.instant #Carga recursos internos utilizando XHR, para mejorar eficiencia en carga de páginas
    - navigation.instant.prefetch #Reduce tiempo de carga percibido al cargar páginas internas cuando la persona se posiciona sobre link
    - navigation.instant.preview #Permite ver recursos internos como un cuadro con descripción base
    - navigation.top #Agrega botón para regresar al inicio
    - navigation.tracking #Sigue la navegación del usuario en la URL
    - content.action.view #Agrega botón de ver fuente
    - content.action.edit #Agrega botón de edición
    - toc.follow #Sigue la navegación del usuario en la tabla de contenidos 
    - toc.integrate #La tabla de contenidos está integrada a la barra de  la izquierda
   



extra:
  alternate: #configuración de idiomas
    - name: Español
      link: /
      lang: es
    - name: English
      link: /en/
      lang: en   
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/socialtic
    - icon: fontawesome/brands/github
      link: https://github.com/socialtic/forensics/
    - icon: material/web
      link: https://socialtic.org

plugins:
  - search  #habilita barra de búsqueda
  - offline #facilita consulta y navegación del sitio offline
  - privacy #plug-in para cargar recursos localmente, reducir tracking

markdown_extensions:
  - admonition #cuadros de texto
  - pymdownx.details #cuadros de texto
  - pymdownx.superfences #cuadros de texto
  - attr_list #permite agregar html dentro del markdown
  - pymdownx.blocks.caption #caption para imágenes

