name: ci
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs Material Insiders
        run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - run: pip install mkdocs-document-dates

      - name: Build docs (default)
        run: mkdocs build -f config/mkdocs.yml

      - name: Build docs (EN)
        run: mkdocs build -f config/en/mkdocs.yml

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated   # change if you configured site_dir: generated
