name: test-ci
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Print hello
        run: echo "Hello from CI on branch $GITHUB_REF"
